AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  christian9a

  Sample SAM Template for christian9a

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
  BookApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: BookApi
      StageName: Prod

  UserApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: UserApi
      StageName: Prod

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  AltaBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: book/AltaBook/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        AltaBookEvent:
          Type: Api
          Properties:
            RestApiId: !Ref BookApi
            Path: /add
            Method: post

  EditBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: book/EditBook/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        EditBookEvent:
          Type: Api
          Properties:
            RestApiId: !Ref BookApi
            Path: /edi
            Method: put

  RecupearLibrosFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: book/RecupearLibros/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        RecuperarLibrosEvent:
          Type: Api
          Properties:
            RestApiId: !Ref BookApi
            Path: /all
            Method: get

  RecuperarLibroFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: book/RecuperarLibro/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        RecuperarLibroEvent:
          Type: Api
          Properties:
            RestApiId: !Ref BookApi
            Path: /search/{idbook}
            Method: post

  EliminarLibroFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: book/EliminarLibro/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        EliminarLibroEvent:
          Type: Api
          Properties:
            RestApiId: !Ref BookApi
            Path: /delete
            Method: delete

  CrearUsuarioFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: CrearUsuario/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        CrearUsuarioEvent:
          Type: Api
          Properties:
            RestApiId: !Ref UserApi
            Path: /add
            Method: post

  AltaPrestamoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Altaprestamo/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        AltaPrestamoEvent:
          Type: Api
          Properties:
            Path: /create_prestamo
            Method: post


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  AltaPrestamoFunctionArn:
    Description: "ARN de la función Lambda para el alta de préstamo"
    Value: !GetAtt AltaPrestamoFunction.Arn
  AltaPrestamoApiUrl:
    Description: "URL de la API Gateway para el evento de alta de préstamo"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create_user"
  CrearUsuarioFunctionArn:
    Description: "ARN de la función Lambda para crear usuarios"
    Value: !GetAtt CrearUsuarioFunction.Arn
  CrearUsuarioApiUrl:
    Description: "URL de la API Gateway para el evento de creación de usuario"
    Value: !Sub "https://${UserApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/add"
